const myMusic=[
    'Bali Bandits - Voulez Vous (Official Music Video)',
    'Chance The Rapper - All Night (Louis The Child Remix)',
    'Corderoy - Close My Eyes (Don Diablo Edit)',
    'Counting_Stars',
    'Daft Punk - Get Lucky (Funk Hunk re-edit)',
    'Deadmau5 - Ghosts & Stuff',
    "Deorro feat. DyCy - Five Hours (Don't Hold Me Back) [Vocal Mix]",
    'Disclosure feat. Eliza Dolittle - You and Me (Flume Remix)',
    'Fritz & Paul Kalkbrenner - Sky and Sand (Original Mix)',
    'Invincible',
    "Outkast - Hey Ya!",
    'song',
    'Stand By Me, Ben E King, 1961',
    'Natos y Waor - CICATRICES',
    'smle - Overflow (feat. Helen Tess) [Official Lyric Video',
    'SMLE ft. Helen Tess - Itll Be Okay',
    'Global Concepts - Robert DeLong',
    'Manel - Al mar',
    'Manel - Aniversari',
    'Weezer - Take On Me (Lyrics)',
    'Party Pupils - Ms. Jackson',
    "Bolier & Diskover - Ain't No Way Around It",
    "Dr. Kucho! & Gregor Salto - Can't Stop Playing (Oliver Heldens & Gregor Salto Remix)",
    'Daft Punk feat. Pharrell & Nile Rodgers - Get Lucky (Full Radio Edit)',

    'AC Slater & Chris Lorenzo - Fly kicks (wax motif remix)',
    'Alesso - I wanna know (Alesso & Deniz Koyu remix)',
    'Bearson - Its not this feat Lemaitre & Josh Pan',
    'Daft Punk - One more time (hotblood remix)',
    'Droeloe - Snow shovels',
    'Duke Dumont - Red light Green light',
    "Dynoro & Gigi dagostino - In my mind",
    'Fall under skies',
    'Florian Picasso - This Is Our Time',
    'Lost frequencies - Sun is shining (deluxe mix)',
    "Louis the child - Last to leave ft Caroline Ailin",
    'Lucky Luke - Cooler than me',
    'Martin Solveig feat Alma - All stars',
    'Metronomy - The look',
    'Nessuno mi puo giudicare - Lost Frequencies remix',
    'ODESZA - A Moment Apart',
    'ODESZA - Higher Ground (feat. Naomi Wild) - Lyric Video',
    'ODESZA - Meridian',
    'ODESZA - Sun Models feat madelyn grant',
    'Paul kalkbrenner - Feed your head',
    'Polo & Pan - Feel good',
    "Post Malone - Circles",
    "Shaed - Trampoline (Jauz remix)",
    'Simon Garfunkel - Mrs Robinson',
    'The Rasmus - In the shadows (Lost Frequencies Deluxe mix)',
    'The Weeknd - Blinding Lights',
    'Two door cinema club - What you know',
    'Van McCoy - The hustle',
    'Justice vs Simian - We are your friends',
    'What so not - High you are (branchez remix)',
    "Y2K & Bbno$ - Lalala (Oliver Heldens remix)",
    'Yeah Yeah Yeahs - Heads Will Rock (A-Trak remix)',
    'Yellow Claw - Good Day ft Dj Snake & Elliphant',
]




